### ISSUE TITLE
Support for choosing a scope that is not the one specified with the SPN

### ISSUE THREAD

**Issue by ajf214** [neilpeterson/azure-blueprints-pipeline-tasks#12]
I'd like to give my SPN access to my root MG, but still choose a different MG or sub to create the blueprint in. Otherwise, I will need to create a unique SPN for each scope where I want to create/manage a blueprint.

The 1.0 version of the extension had support for this, which I think worked well.

**Comment by neilpeterson** [comment]
@ajf214 I've worked in experiences for alternate child subscriptions. It's not perfect. If you have any suggestions I would be happy to update.

## Create

If the task is scoped to a management group, to create the blueprint at a child subscription, select the 'Create Blueprint at child subscription' box and add the subscription ID.

![image](https://user-images.githubusercontent.com/7844635/57641903-fd68d580-756a-11e9-9c7c-5b9847f0efda.png)

## Assign

This task will search both the Management Group and target Subscription for a Blueprint with a name match. If a Blueprint is found at both the Management Group and Subscription, the Subscription is used.

I had hoped that if this task is scoped to a subscription, that the subscription ID could be derived from the service connection and that target subscription argument could be hidden. However, this is not possible with the current pipeline task SDK.

![image](https://user-images.githubusercontent.com/7844635/57642145-7a944a80-756b-11e9-9861-f7fc142a3813.png)

I am closing the issue, feel free to re-open with updated requests etc..
