### ISSUE TITLE
Clean out artifacts before a blueprint update

### ISSUE THREAD

**Issue by ajf214** [neilpeterson/azure-blueprints-pipeline-tasks#13]
If the blueprint already exists, the task should delete all existing artifacts. Otherwise artifacts from old versions of the source code will remain in the blueprint. The source code should be the source of truth, so the blueprint should always have *only* the artifacts that are in source. The API does not natively support this, so artifacts will need to be manually cleaned out by the task before a new set of artifacts is uploaded.

**Comment by neilpeterson** [comment]
@ajf214 I've added this functionality in this PR. I will merge and publish the updated extension after Build.

https://github.com/neilpeterson/azure-blueprints-pipeline-tasks/pull/17

**Comment by neilpeterson** [comment]
@ajf214 v1.1.f has been published which includes this functionality.
