### ISSUE TITLE
assignBlueprint should wait until assignment reaches terminal state

### ISSUE THREAD

**Issue by alex-frankel** [neilpeterson/azure-blueprints-pipeline-tasks#14]
Today the task "succeeds" if the PUT succeeds, but it should only succeed if the assignment itself succeeds. The task will need to wait and continue to check until the blueprint either succeeds or fails. If the assignment fails, it should print out the error and the task should fail

**Comment by neilpeterson** [comment]
Work is almost complete, need to test and will merge.

https://github.com/neilpeterson/azure-blueprints-pipeline-tasks/blob/assignment-validation-loop/assignBlueprint/assignBlueprint.ps1#L76

**Comment by neilpeterson** [comment]
@alex-frankel assignment wait has been added in https://github.com/neilpeterson/azure-blueprints-pipeline-tasks/commit/c7e5c3cd1a110258f1010048ef3244395672cab2 . This is an optional wait with a configurable timeout. Currently, a generic error is logged on assignment failure.
