### ISSUE TITLE
Update to latest api version

### ISSUE THREAD

**Issue by alex-frankel** [neilpeterson/azure-blueprints-pipeline-tasks#15]
We are currently on 2018-11-01-preview

**Comment by neilpeterson** [comment]
@alex-frankel Updated in this PR. I will merge and re-publish the extension after Build.

https://github.com/neilpeterson/azure-blueprints-pipeline-tasks/pull/17

**Comment by neilpeterson** [comment]
@alex-frankel I've just published v1.1.4 which includes the updated api version.
