### ISSUE TITLE
Is it possible to get the Blueprint ID without the Management Group name

### ISSUE THREAD

**Issue by neilpeterson** [neilpeterson/azure-blueprints-pipeline-tasks#2]
When assigning a blueprint, we need the blueprint ID. If the blueprint was created at a management group, the ID includes the management group name. I see that the PowerShell module can list all blueprints, can we also do this .via REST?

https://docs.microsoft.com/en-us/powershell/module/az.blueprint/get-azblueprint?view=azps-1.6.0

**Comment by alex-frankel** [comment]
No I don't believe this is possible via rest today. I think in the powershell modules we are just iterating through all the scopes through the API.
