### ISSUE TITLE
ParametersFile required.

### ISSUE THREAD

**Issue by Plork** [neilpeterson/azure-blueprints-pipeline-tasks#22]
```
{
  "name": "ParametersFile",
  "type": "string",
  "label": "Parameters File Path",
  "defaultValue": "",
  "required": true,
  "helpMarkDown": "Should be fully qualified path or relative to the default working directory."
},
```

should this be required? You can make blueprints without parameters.

**Comment by Plork** [comment]
nvm, it's not only parameters. It's a collection of the required input for an assignment.

**Comment by neilpeterson** [comment]
@Plork thanks for raising this. You are correct, I believe the file is necessary. I named it ParametersFile just to give it a friendly name. If you have any other suggestions, we can update the name etc..

I'm going to close the issue, feel free to open back up, suggest a new name, or even submit a PR to update.

Thanks
