### ISSUE TITLE
A reason not to use az.Blueprint?

### ISSUE THREAD

**Issue by Plork** [neilpeterson/azure-blueprints-pipeline-tasks#24]
Is there a reason not use  Az.Blueprint? I know it's nice to have a job that can run cross platform. But once Powershell.Core is available as a task handler this shouldn't be an issue anymore and then this could be written for pwsh 6 +

Seems like a LOT of work to rewrite this
https://github.com/Azure/azure-powershell/tree/master/src/Blueprint

Into typescript.

I changed the assignment script into the Az cmd-let myself because I wanted a way during a release to specify the version of the blueprint that is going to be assigned. The current uri you are using to get the blueprint does not return versions.

https://management.azure.com/providers/Microsoft.Management/managementGroups/{0}/providers/Microsoft.Blueprint/blueprints/{1}?api-version=2018-11-01-preview

**Comment by neilpeterson** [comment]
@Plork can you share your updated assignment script? Several issues are stacking up, related to assignment, and I agree that it will be quite a bit of work to recreate the PowerShell module logic. 

If you have something that you can contribute here, I would be happy to review and potentially merge in here.

**Comment by alex-frankel** [comment]
It is a good point. We've also discussed generating a JS SDK instead of direct API calls, but there will probably be work associated there as well that powershell has already covered. If we can use Az.Blueprint, that would be great, but I don't know what all the implications of that would be.

One more point, Az.Blueprint is going to get an update this week which will have full CRUD operation coverage for both the blueprint definition and assignment.

**Comment by Plork** [comment]
So that means we can use the cmdlet for the creations as well. I didn't rewrite that yet.

Here is the branch I am working on at the moment.
https://github.com/Plork/azure-blueprints-pipeline-tasks/tree/feature/az_cmdlets

It's not 100% tested yet since I was struggling with getting powershell 6 and the az module to work on a hosted agent. So the problem is that the task handler for azure devops does not support pwsh (core) yet on windows hosts. I could try and get it to work on a linux agent and it "should" automagicly work on a windows agent then as well. (developing it on mac at the moment)

In the other issue I linked I have a working version of calling the api directly.
https://github.com/neilpeterson/azure-blueprints-pipeline-tasks/issues/25

**Comment by neilpeterson** [comment]
@Plork these activities have been updated to use Az.Blueprints (both create and assign). Thanks for weighing in here and for the issue.

https://github.com/neilpeterson/azure-blueprints-pipeline-tasks/commit/c7e5c3cd1a110258f1010048ef3244395672cab2
