### ISSUE TITLE
Assign specific versions of blueprints

### ISSUE THREAD

**Issue by Plork** [neilpeterson/azure-blueprints-pipeline-tasks#25]
I would like the assignment of blueprints to have a version field so i can either assign the latest published blueprint or a specific version.

This way I can have a proper Ci/Cd based on the build / release of the blueprint. 

This also makes it possible to rollback an older blueprint.

**Comment by Plork** [comment]
I have an attempt on this forked on my github. (still work in progress)

https://github.com/Plork/azure-blueprints-pipeline-tasks/tree/feature/release_versions

**Comment by neilpeterson** [comment]
@Plork this has been added to 1.2.1.

https://github.com/neilpeterson/azure-blueprints-pipeline-tasks/commit/c7e5c3cd1a110258f1010048ef3244395672cab2
