### ISSUE TITLE
Only works with windows build agents

### ISSUE THREAD

**Issue by alex-frankel** [neilpeterson/azure-blueprints-pipeline-tasks#28]
the az.blueprint module is written for powershell core, so it should work cross-platform. If I try to switch to a linux hosted agent I get this error:

![image](https://user-images.githubusercontent.com/11078275/60825782-561ab000-a161-11e9-9337-f231c761ad99.png)

**Comment by neilpeterson** [comment]
My guess is that this is related to the [VstsTaskSDK commands](https://github.com/neilpeterson/azure-blueprints-pipeline-tasks/tree/master/createBlueprint/ps_modules/VstsTaskSDK) used for internal things. For instance, gathering creds from the Azure Pipeline service connection.

This looks related, I will follow up.

https://github.com/Microsoft/azure-pipelines-agent/issues/1416

**Comment by neilpeterson** [comment]
At this time there is no plan to support the VstsTaskSDK command in Linux.

I will keep my eye open for any changes and / or alternate opportunities here.

Closing the issue for now.
