### ISSUE TITLE
[error]A positional parameter cannot be found that accepts argument

### ISSUE THREAD

**Issue by Astashin** [neilpeterson/azure-blueprints-pipeline-tasks#33]
If a project contains space, createBlueprint.ps1 fails with subj error. 
The possible reason: lack of single quotes ' for $BlueprintName parameter to handle spaces in paths:

Invoke-Expression "Import-AzBlueprintWithArtifact -Name $BlueprintName -InputPath $BlueprintPath $BlueprintScope -Force"

**Comment by neilpeterson** [comment]
@Jagstangushka thanks for entering this issue. I am looking into it now.

**Comment by neilpeterson** [comment]
Fix is in version 1.5.5.

https://github.com/neilpeterson/azure-blueprints-pipeline-tasks/pull/47

Thanks again for raising the issue.
