### ISSUE TITLE
Exclude a principal from a deny assignment when using resource group locks

### ISSUE THREAD

**Issue by yogspatel** [neilpeterson/azure-blueprints-pipeline-tasks#40]
Current documentation states excluding a principle from a deny assignment using resource group locks can only be done via REST API (https://docs.microsoft.com/bs-latn-ba/azure/governance/blueprints/concepts/resource-locking)

Does this task support the use of passing json body (as documented in link above) to invoke the rest api, or is their a mechanism to achieve resource group locking and exclusion of principles via this task and the blueprint assignment? 

Thank You

Yogesh

**Comment by alex-frankel** [comment]
Yes, the task accepts a property called `ParametersFile`, which is where the excluded principals property is specified.

Take a look here: https://docs.microsoft.com/en-us/azure/governance/blueprints/how-to/manage-assignments-ps#create-blueprint-assignments

If you scroll down to Example 2, you will see an example AssignmentFile that shows you where to put the ExcludedPrincipals:

```json
{
  "identity": {
    "type": "SystemAssigned"
  },
  "location": "westus2",
  "properties": {
    "description": "Assignment of the 101-blueprint-definition-subscription",
    "blueprintId": "/subscriptions/{subId}/providers/Microsoft.Blueprint/blueprints/101-blueprints-definition-subscription",
    "locks": {
      "mode": "AllResourcesReadOnly",
      "excludedPrincipals": [
          "7be2f100-3af5-4c15-bcb7-27ee43784a1f",
          "38833b56-194d-420b-90ce-cff578296714"
      ]
    },
    "parameters": {
      "storageAccount_storageAccountType": {
        "value": "Standard_GRS"
      }
    },
    "resourceGroups": {
      "ResourceGroup": {
        "name": "storage_rg",
        "location": "westus2"
      }
    }
  }
}
```

**Comment by neilpeterson** [comment]
Thanks @alex-frankel 

@yogspatel  I am going to close this issue. If you need any followup or believe that your issue has not been addressed, please let me know and we can adjust.
