### ISSUE TITLE
Asign BluePrint with Params that has multiple "json" levels.

### ISSUE THREAD

**Issue by Plork** [neilpeterson/azure-blueprints-pipeline-tasks#42]
When you assign a blueprint that has a parameter that has a json block as value it will fail when there are more then 2 json levels.

```
$body = Get-Content -Raw -Path $AssignmentFilePath | ConvertFrom-Json
```

`ConvertFrom-Json` default to 2 if I remembered correctly.

This could easily be solved by adding `-depth 10`

**Comment by neilpeterson** [comment]
PR has been merged. I will close this issue once a new release has been created.

**Comment by neilpeterson** [comment]
@Plork can you share an assignment file with multiple levels of JSON? I am trying to wrap my head around a few things but do not have a handy example to work with.

Thanks

**Comment by Plork** [comment]
Sure for example we specify the network rules as an object.
So one of the parameters of the assignment file is the following:

```
"NetworkRules": {
                "value": [
                    {
                        "name": "AccessRule",
                        "properties": {
                            "priority": "1000",
                            "action": {
                                "type": "Allow"
                            },
                            "rules": [
                                {
                                    "name": "AllowAllToDns",
                                    "protocols": [
                                        "Any"
                                    ],
                                    "sourceAddresses": [
                                        "1.2.3.4/17"
                                    ],
                                    "destinationAddresses": [
                                        "1.2.3.4/32",
                                        "1.2.3.4/32"
                                    ],
                                    "destinationPorts": [
                                        "53"
                                    ]
                                },
                                {
                                    "name": "AllowBackend",
                                    "protocols": [
                                        "Tcp"
                                    ],
                                    "sourceAddresses": [
                                        "1.2.3.4/24"
                                    ],
                                    "destinationAddresses": [
                                        "1.2.3.4/24"
                                    ],
                                    "destinationPorts": [
                                        "12345",
                                        "23456"
                                    ]
                                }
                            ]
                        }
                    }
                ]
            }
```

Everything works until "properties"
the value of properties isn't translated to a hashtable in powershell but kept as a json inside a "value"

**Comment by neilpeterson** [comment]
@Plork I've been playing around converting json > object > and back to json. It seems to me that the depth needs to be updated when converting the object back to a JSON string `ConvertTo-Json` vs. when converting to the PowerShell object `ConvertFrom-Json`.

I've updated the pipeline task (1.5.4), but cannot filly test because I do not have a blueprint utilizing nest JSON.

[updated code](https://github.com/neilpeterson/azure-blueprints-pipeline-tasks/blob/master/assignBlueprint/assignBlueprint.ps1#L84) 

Can you give it shot and let me know how it works out?

**Comment by Plork** [comment]
Yes you are right it should be at the convert to.

I will test the code and let you know

**Comment by neilpeterson** [comment]
Thanks - if this is not resolved, let me know and I will re-open the issue.
