### ISSUE TITLE
GetAssignment fail when TargetSubscriptionId

### ISSUE THREAD

**Issue by Plork** [neilpeterson/azure-blueprints-pipeline-tasks#56]
When you supply a TargetSubscriptionId it will always try "New-AzBlueprintAssignment" since the `Get-` defaults to the subscriptionId of the supplied Service Connection.

```
[error]An assignment with name '$AssignmentName' in subscription '/subscriptions/$TargetSubscriptionID' already exists. 
Please use Set-AzBlueprintAssignment to update an existing assignment.
```

Also the $TargetSubscriptionID is used in the script even though it is an optional argument according to the task.json.

I would like the `Get-` to look at the TargetSubscriptionId and that it falls back to the SubscriptionId of the service connection when not provided.

**Comment by neilpeterson** [comment]
@Plork I've done a little updating on the PR you've submitted for this. In your PR, the assumption is that the service connection is scoped to a subscription. However, service connections for these tasks can be scoped to either a subscription or a management group. 

The updated code starts [here](https://github.com/neilpeterson/azure-blueprints-pipeline-tasks/blob/master/assignBlueprint/assignBlueprint.ps1#L56).

Essentially:

- If the service connection is scoped to a subscription, use the subscription ID from the service connection.
- If the service connection is scoped to a management group, ensure that a subscription ID has been specified and use that one. If one has not been specified, throw an error.

 The UI is a little clunky on this, if you have any suggestions, feel free to create an issue / PR / etc..

These changes are in the [1.6.0 release](https://github.com/neilpeterson/azure-blueprints-pipeline-tasks/releases/tag/1.6.0).

Thanks
