### ISSUE TITLE
Is there a way to set 'complete' mode at the blueprint level?

### ISSUE THREAD

**Issue by danialgoodwin** [neilpeterson/azure-blueprints-pipeline-tasks#66]
I see how to set 'complete' mode for individual ARM templates, but not for blueprints.

Documentation: https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/deployment-modes#complete-mode

**Comment by alex-frankel** [comment]
there is no way to set complete mode for ARM templates deployed via blueprints today. This is not something we are planning to change at the moment.

**Comment by neilpeterson** [comment]
Thanks @alex-frankel. 

@danialgoodwin I am going to close the issue and will re-open if the situation changes.

**Comment by sethwenzel** [comment]
In case anyone else stumbles across this -- i've added a uservoice suggestion about this -- https://feedback.azure.com/forums/915958-azure-governance/suggestions/40532152-blueprints-and-arm-complete-mode
